version: '3.7'

services:
  app:
    build: .
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "3000:3000"
    volumes:
      - /usr/src/node_modules
      - .:/usr/src
         
