version: '3.7'

services:
  app:
    build: .
    environment:
      DATABASE_URL: "mysql://user:password@localhost:3306/db_name"
    ports:
      - "3000:3000"
    volumes:
      - /usr/src/node_modules
      - .:/usr/src
         
